import { Branch, Company } from "./company";
import { Payment } from "./payment";
import { Product } from "./product";
import { Supplier } from "./supplier";

export type InvoiceSupplier = {
  invoice_supplier_id: string,
  invoice_supplier_origin_id: string,
  branch_id: string,
  company_id: string,
  supplier_id: string,
  user_id: string,
  invoice_supplier_name: string,
  invoice_supplier_branch_name: string,
  invoice_supplier_company_name: string,
  invoice_supplier_account: string,
  invoice_supplier_license_plate: string,
  invoice_supplier_date: Date | string,
  invoice_supplier_contact: string,
  invoice_supplier_weight: any,
  invoice_supplier_price: any,
  invoice_supplier_vat_type: 'exc' | 'inc',
  invoice_supplier_vat_rate: any,
  invoice_supplier_vat_price: any,
  invoice_supplier_net_price: any,
  invoice_supplier_key_by: string,
  invoice_supplier_key_date: Date | string,
  invoice_supplier_paid_date: Date | string,
  invoice_supplier_paid_type: string,
  invoice_supplier_remark: string,
  invoice_supplier_status: string,
  addby?: string,
  adddate?: Date,
  updateby?: string,
  lastupdate?: Date,
  invoice_supplier_lists?: InvoiceSupplierList[],
  bank_name?: string,
  branch_name?: string,
  user_fullname?: string,
  payments?: Payment[],
};

export type InvoiceSupplierList = {
  invoice_supplier_list_id: string,
  invoice_supplier_id: string,
  product_id: string,
  invoice_supplier_list_name: string,
  invoice_supplier_list_qty: any,
  invoice_supplier_list_weight: any,
  invoice_supplier_list_deweight_quality: any,
  invoice_supplier_list_deweight_percent: any,
  invoice_supplier_list_deweight_compensation: any,
  invoice_supplier_list_net_weight: any,
  invoice_supplier_list_unit_name: string,
  invoice_supplier_list_unit_price: any,
  invoice_supplier_list_unit_promotion_price: any,
  invoice_supplier_list_unit_shipping_price: any,
  invoice_supplier_list_unit_other_price: any,
  invoice_supplier_list_price: any,
  invoice_supplier_list_remark: string,
};

export type InvoiceSupplierProduct = {
  branch_id: string,
  company_id: string,
  product_id: string,
  supplier_id: string,
  invoice_supplier_id: string,
  invoice_supplier_origin_id: string,
  invoice_supplier_date: Date | string,
  invoice_supplier_list_name: string,
  invoice_supplier_list_qty: any,
  invoice_supplier_list_weight: any,
  invoice_supplier_list_deweight_quality: any,
  invoice_supplier_list_deweight_percent: any,
  invoice_supplier_list_deweight_compensation: any,
  invoice_supplier_list_net_weight: any,
  invoice_supplier_list_unit_name: string,
  invoice_supplier_list_unit_price: any,
  invoice_supplier_list_unit_promotion_price: any,
  invoice_supplier_list_unit_shipping_price: any,
  invoice_supplier_list_unit_other_price: any,
  invoice_supplier_list_price: any,
  invoice_supplier_list_remark: string,
  branch?: Branch,
  company?: Company,
  product?: Product,
  supplier?: Supplier,
}